apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: placeholder-hf-cache-pvc
  namespace: vllm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: placeholder-vllm-model-storage-pvc
  namespace: vllm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 2Ti
